/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 sculpture.glb 
Author: dennisonb (https://sketchfab.com/dennisonb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sculpture-a6f979a58cbd43329734c201a63d50f1
Title: Sculpture
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function SculptureModel(props) {
  const { nodes, materials } = useGLTF("/sculpture.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/sculpture.glb");
